# Generated by Django 5.2.2 on 2026-03-14 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0011_containergithub'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='container',
            field=models.ForeignKey(blank=True, help_text='Container linked to this RTSP task', null=True, on_delete=django.db.models.deletion.SET_NULL, to='predictor.container'),
        ),
        migrations.AddField(
            model_name='task',
            name='fps',
            field=models.IntegerField(blank=True, help_text='Frames per second to capture', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='rtsp_url',
            field=models.CharField(blank=True, help_text='RTSP URL for streaming', max_length=500, null=True),
        ),
    ]
