# Generated by Django 5.2.2 on 2026-03-14 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0012_task_container_task_fps_task_rtsp_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_clip', models.FileField(blank=True, null=True, upload_to='container_anomalies/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('label', models.CharField(default='Suspicious', max_length=100)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='predictor.task')),
            ],
        ),
    ]
